import { esc, head } from './layout'

// NOTE: These texts are a starting point written for a B2B legal-software provider in Oman.
// They must be reviewed and approved by the company's own counsel before public launch.
const LAST_UPDATED = '30 September 2026'

const terms = (support: string) => `
<h1>Terms of Service</h1>
<p class="muted">Last updated: ${LAST_UPDATED}</p>
<p>These Terms govern access to and use of the TrustiqLegal platform (the "Service") by the organization that registers an account (the "Customer") and its authorized users. By creating an account or using the Service, the Customer agrees to these Terms.</p>
<h2>1. The Service</h2>
<p>TrustiqLegal provides software for legal practice management, including matter and client records, document storage, calendaring, and AI-assisted drafting, research and document review. The Service is a tool for qualified legal professionals.</p>
<h2>2. No legal advice</h2>
<p>TrustiqLegal is not a law firm and does not provide legal advice. Output generated by AI features may be incomplete, outdated or incorrect, and may reference provisions that must be verified. The Customer and its users remain solely responsible for reviewing all output and for any advice given to their own clients.</p>
<h2>3. Accounts and users</h2>
<p>The Customer is responsible for its users, for keeping credentials confidential, and for all activity under its account. Account owners and administrators control who may access the Customer's workspace.</p>
<h2>4. Customer data</h2>
<p>The Customer retains all rights in the data and documents it uploads or creates ("Customer Data"). We process Customer Data only to provide, secure and support the Service, as described in our <a href="/privacy">Privacy Policy</a>. Customer Data is not used to train AI models. The Customer can export its data at any time from the workspace settings.</p>
<h2>5. Acceptable use</h2>
<p>The Customer must not use the Service unlawfully, upload content it has no right to process, attempt to breach security or access other customers' data, or resell the Service without our written agreement.</p>
<h2>6. Trials, plans and fees</h2>
<p>New workspaces receive a free trial. After the trial, continued write access requires a paid plan. Fees, plan limits and billing terms are set out in the applicable order form or pricing page. Fees are exclusive of applicable taxes, including VAT.</p>
<h2>7. Availability and support</h2>
<p>We aim to keep the Service available and will make reasonable efforts to schedule maintenance outside business hours in the Gulf region. Service levels, where agreed, are set out in the Customer's order form.</p>
<h2>8. Confidentiality and security</h2>
<p>Each party will protect the other's confidential information with reasonable care. We apply technical and organizational measures appropriate to legal data, including encryption in transit, access controls and audit logging.</p>
<h2>9. Liability</h2>
<p>To the maximum extent permitted by law, neither party is liable for indirect or consequential loss, and each party's total liability is limited to the fees paid by the Customer in the twelve months before the claim, except for liability that cannot be limited by law.</p>
<h2>10. Termination</h2>
<p>The Customer may stop using the Service at any time. Either party may terminate for material breach not cured within thirty days of notice. On termination, the Customer may export its data for thirty days, after which it will be deleted from active systems.</p>
<h2>11. Governing law</h2>
<p>These Terms are governed by the laws of the Sultanate of Oman. Disputes will be submitted to the competent courts of Muscat, unless the parties agree otherwise in writing.</p>
<h2>12. Contact</h2>
<p>Questions about these Terms: <a href="mailto:${esc(support)}">${esc(support)}</a>.</p>`

const privacy = (support: string) => `
<h1>Privacy Policy</h1>
<p class="muted">Last updated: ${LAST_UPDATED}</p>
<p>This policy explains how TrustiqLegal processes personal data in connection with the Service, including under the Personal Data Protection Law of the Sultanate of Oman (Royal Decree 6/2022) and other applicable GCC data-protection laws.</p>
<h2>1. Roles</h2>
<p>For account information about our customers' users, we act as controller. For Customer Data (clients, matters, documents), the Customer is the controller and we act as its processor, following the Customer's instructions.</p>
<h2>2. Data we process</h2>
<ul>
<li>Account data: names, email addresses, roles, language preference, hashed passwords.</li>
<li>Security data: sign-in times, IP addresses, browser user agent, and an audit trail of actions in the workspace.</li>
<li>Customer Data: information the Customer enters or uploads about its clients, matters and documents.</li>
</ul>
<h2>3. How we use it</h2>
<p>To provide and secure the Service, authenticate users, send service emails (such as invitations and password resets), provide support, and meet legal obligations. We do not sell personal data and we do not use Customer Data to train AI models.</p>
<h2>4. AI processing</h2>
<p>When a user invokes an AI feature, the relevant text (for example, the question, the case summary or the document being reviewed) is sent to our AI model provider solely to generate the response. Providers are contractually restricted from using this data to train their models.</p>
<h2>5. Sub-processors</h2>
<p>We use hosting, database, email-delivery and AI-model providers. A current list is available on request from <a href="mailto:${esc(support)}">${esc(support)}</a>.</p>
<h2>6. International transfers</h2>
<p>Where data is processed outside the Customer's country, we rely on the transfer mechanisms and safeguards required by applicable law.</p>
<h2>7. Retention</h2>
<p>Customer Data is kept for the life of the account and deleted from active systems within thirty days after termination, subject to backup cycles. Security logs are retained for up to twelve months.</p>
<h2>8. Security</h2>
<p>Passwords are stored as salted hashes, traffic is encrypted in transit, access is role-based, and administrative actions are logged.</p>
<h2>9. Your rights</h2>
<p>Individuals may request access to, correction of, or deletion of their personal data, or object to its processing. Requests about Customer Data should be directed to the relevant Customer (law firm); we will assist them. Other requests: <a href="mailto:${esc(support)}">${esc(support)}</a>.</p>
<h2>10. Changes</h2>
<p>We will notify account owners of material changes to this policy.</p>`

const notFoundBody = `
<h1>Page not found</h1>
<p>The page you are looking for does not exist.</p>
<p><a href="/">Return to the home page</a> or <a href="/app">open the app</a>.</p>`

export function legalPage(kind: 'terms' | 'privacy' | '404', opts: { assetVersion: string; supportEmail: string }) {
  const title = kind === 'terms' ? 'Terms of Service' : kind === 'privacy' ? 'Privacy Policy' : 'Page not found'
  const body = kind === 'terms' ? terms(opts.supportEmail) : kind === 'privacy' ? privacy(opts.supportEmail) : notFoundBody
  return `<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>${head({ title: `${title} – TrustiqLegal`, assetVersion: opts.assetVersion })}</head>
<body class="bg-white text-slate-800">
  <header class="border-b border-slate-200">
    <div class="max-w-3xl mx-auto px-4 h-16 flex items-center justify-between">
      <a href="/" class="flex items-center gap-2 font-bold text-brand-900"><i class="fas fa-scale-balanced"></i> TrustiqLegal</a>
      <a href="/app" class="text-sm font-medium text-brand-700 hover:underline">Sign in</a>
    </div>
  </header>
  <main class="prose-legal max-w-3xl mx-auto px-4 py-12">${body}</main>
</body>
</html>`
}
